#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

OUTPUT=$(pwd)/.drivers
mkdir -p $OUTPUT
rm -rf $OUTPUT/*

unset -v LIBCUDA_PATH

# find libcuda.so
LIBCUDA_PATH=$(whereis libcuda.so | cut -d " " -f2)

if [ ! -z $LIBCUDA_PATH ]; then
    echo "Using libcuda.so: $LIBCUDA_PATH"

    LIBCUDA_SHA256=$(sha256sum $LIBCUDA_PATH | head -c 64)
    cp $LIBCUDA_PATH $OUTPUT/libcuda.so
    CUDA_CONFIG="
        \"cuda\" : {
            \"path\" : \"libcuda.so\",
            \"sha256\" : \"$LIBCUDA_SHA256\"
        }
    "
fi

unset -v NVIDIA_DRIVER

NVIDIA_EGL_PATH=$(whereis libEGL_nvidia.so.0 | cut -d " " -f2)

if [ ! -z $NVIDIA_EGL_PATH ]; then
    echo "Using libEGL_nvidia.so: $NVIDIA_EGL_PATH"
    NVIDIA_SHA256=$(sha256sum $NVIDIA_EGL_PATH | head -c 64)

    cp $NVIDIA_EGL_PATH $OUTPUT/libEGL_nvidia.so.0

    NVIDIA_CONFIG="
        {
            \"name\": \"nvidia\",
            \"path\": \"libEGL_nvidia.so.0\",
            \"sha256\" : \"$NVIDIA_SHA256\"
        }
    "
fi

echo "
    {
        $CUDA_CONFIG
        \"drivers\" = [
            $NVIDIA_CONFIG
        ]
    }
" > $OUTPUT/config.json

# Mask any top-level git ignores
echo "
!*.so
!config.json
.gitignore
" > $OUTPUT/.gitignore

# Track for the flake, but do not add
git add --intent-to-add .drivers/*
git update-index --assume-unchanged .drivers/*