#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# This will load the non-wandb environment variables
export $(cat $SCRIPT_DIR/../.env | xargs)

ENV=$(which env)
exec $ENV $@
